name: by_ui_workspace
repository: https://github.com/arybayunurwicaksono/By_UI

packages:
  - packages/*
  - apps/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze .
    description: Run flutter analyze across all packages and apps.

  test:
    exec: flutter test
    description: Run flutter test in all packages with test suite.
    packageFilters:
      dirExists: test

  clean:
    exec: flutter clean
    description: Clean build cache in all apps and packages.
